### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by lukehsiao** [xiao-cheng/table-extraction#7]
When I run table-extraction on MOTOS03160.pdf, I see this error:
```
+ python ../udf/table-extraction/parse.py pdf/MOTOS03160-1.pdf
+ deepdive sql 'COPY table_dump FROM STDIN'
Traceback (most recent call last):
  File "/home/lh/repos/HardwareDeepDive/udf/table-extraction/pdf/pdf_parsers.py", line 129, in analyze_pages
    interpreter.process_page(page)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 832, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 843, in render_contents
    self.init_resources(resources)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 347, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 177, in get_font
    font = PDFType1Font(self, spec)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdffont.py", line 575, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdffont.py", line 534, in __init__
    self.cid2unicode = EncodingDB.get_encoding(name, diff)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/encodingdb.py", line 61, in get_encoding
    cid2unicode[cid] = name2unicode(x.name)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/encodingdb.py", line 21, in name2unicode
    return unichr(int(m.group(0)))
OverflowError: Python int too large to convert to C long
```

I saw this when I changed init.sh in HardwareDeepDive to input all of the PDFs:
```
INPUT_FILES=pdf/*

# This loops through all of the files in pdf/ and adds them to table_dump
for f in $INPUT_FILES
do
  echo "[info] Loading $f..."
  python ../udf/table-extraction/parse.py $f | deepdive sql "COPY table_dump FROM STDIN"
done
cat create_tables.sql | deepdive sql
```

**Comment by xiao-cheng** [comment]
Is there a pdfminer directory in your table-extraction root dir? I removed the dependency on the default pdfminer installed through pip precisely for this bug.

**Comment by lukehsiao** [comment]
Yes, there is. I just uninstalled pdfminer, and now I see this error:
```
+ python ../udf/table-extraction/parse.py pdf/RECTS01325-1.pdf
+ deepdive sql 'COPY table_dump FROM STDIN'
Traceback (most recent call last):
  File "../udf/table-extraction/parse.py", line 7, in <module>
    from pdf.pdf_utils import *
  File "/home/lh/repos/HardwareDeepDive/udf/table-extraction/pdf/pdf_utils.py", line 10, in <module>
    from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTFigure, LTChar, LTImage,\
ImportError: No module named pdfminer.layout
```
So, it seems like python isn't seeing the dependency in the local dir.

**Comment by xiao-cheng** [comment]
Ah I see, the current version works for me for some reason when it shouldn't. Can you create a symlink for now:
ln -s /home/lh/repos/HardwareDeepDive/udf/table-extraction/pdfminer /home/lh/repos/HardwareDeepDive/udf/table-extraction/pdf/pdfminer

I'll need to move the pdf_utils.py out of the /pdf subdir since python only resolves sibling/child directories and not any root or parent directories.

**Comment by lukehsiao** [comment]
I've added the symlink  by running the command you provided. This creates a symlink to pdfminer inside the /table-extraction/pdf directory, but I still get the import error:
```
+ python ../udf/table-extraction/parse.py pdf/BC337.pdf
+ deepdive sql 'COPY table_dump FROM STDIN'
Traceback (most recent call last):
  File "../udf/table-extraction/parse.py", line 7, in <module>
    from pdf.pdf_utils import *
  File "/home/lh/repos/HardwareDeepDive/udf/table-extraction/pdf/pdf_utils.py", line 10, in <module>
    from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTFigure, LTChar, LTImage,\
ImportError: No module named pdfminer.layout
```
I'm running on 64-bit Ubuntu version 14.04.3 LTS using Python 2.7.6 if that helps.

**Comment by lukehsiao** [comment]
Ran through all the input PDFs fine. The symlink works for now. Thanks!
